spring:
  application:
    name: zuul-edge-server
  profiles:
    active: localhost
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service/
          predicates:
            - Path=/api/1.0/product/**
        - id: product-cache-service
          uri: lb://product-cache-service/
          predicates:
            - Path=/api/1.0/product-cache/**




server:
  port: 8762


---
spring:
  config:
    active:
      on-profile: localhost


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}



